/** Translate-domain IpcApi error codes. Import directly from this module on both sides. */
export const translateErrorCodes = {
  PDF_DEPENDENCY_NOT_INSTALLED: 'PDF_TRANSLATION_DEPENDENCY_NOT_INSTALLED',
  PDF_DEPENDENCY_OUTDATED: 'PDF_TRANSLATION_DEPENDENCY_OUTDATED',
  PDF_OCR_REQUIRED: 'PDF_TRANSLATION_OCR_REQUIRED',
  PDF_RESULT_PERSIST_FAILED: 'PDF_TRANSLATION_RESULT_PERSIST_FAILED'
} as const
