/** Generates docs/README.md from doc frontmatter so the index cannot drift from the tree. `--check` verifies instead of writing. */
import * as fs from 'fs'
import matter from 'gray-matter'
import * as path from 'path'

import { listMarkdownFiles } from './verify-doc-frontmatter'

const ROOT = path.resolve(__dirname, '..')

const SECTION_TITLES: Record<string, string> = {
  ai: 'AI',
  'api-gateway': 'API Gateway',
  i18n: 'i18n',
  ipc: 'IPC',
  'lan-transfer': 'LAN Transfer'
}

const titleForDomain = (domain: string): string =>
  SECTION_TITLES[domain] ??
  domain
    .split('-')
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join(' ')

/** The doc's H1 text; falls back to the filename stem when no H1 exists. */
export const docTitle = (filePath: string): string => {
  const { content } = matter(fs.readFileSync(filePath, 'utf8'))
  const heading = content.match(/^# (.+)$/m)
  return heading ? heading[1].trim() : path.basename(filePath, '.md')
}

const docDescription = (filePath: string): string => {
  const { data } = matter(fs.readFileSync(filePath, 'utf8'))
  return typeof data.description === 'string' ? data.description.trim() : ''
}

const tableRows = (docsDir: string, files: string[]): string[] =>
  files.map((file) => {
    const link = './' + path.relative(docsDir, file).split(path.sep).join('/')
    return `| [${docTitle(file)}](${link}) | ${docDescription(file)} |`
  })

/** README first, then alphabetical; nested files after top-level ones. */
const domainOrder = (domainDir: string, files: string[]): string[] => {
  const depth = (file: string) => file.split(path.sep).length
  return [...files].sort((a, b) => {
    const aReadme = path.dirname(a) === domainDir && path.basename(a) === 'README.md' ? 0 : 1
    const bReadme = path.dirname(b) === domainDir && path.basename(b) === 'README.md' ? 0 : 1
    return aReadme - bReadme || depth(a) - depth(b) || a.localeCompare(b)
  })
}

export const generateIndex = (repoRoot: string): string => {
  const docsDir = path.join(repoRoot, 'docs')
  const lines: string[] = [
    '# Cherry Studio Documentation',
    '',
    '<!-- Generated by scripts/gen-doc-index.ts — do not edit by hand; run `pnpm docs:index`. -->',
    '',
    '## Contrib',
    '',
    '| Document | Description |',
    '|----------|-------------|',
    '| [Contributing](../CONTRIBUTING.md) | How to contribute code |',
    ...tableRows(docsDir, listMarkdownFiles(path.join(docsDir, 'contrib'))),
    '',
    '## References'
  ]

  const referencesDir = path.join(docsDir, 'references')
  const domains = fs
    .readdirSync(referencesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()

  for (const domain of domains) {
    const domainDir = path.join(referencesDir, domain)
    lines.push('', `### ${titleForDomain(domain)}`, '', '| Document | Description |', '|----------|-------------|')
    lines.push(...tableRows(docsDir, domainOrder(domainDir, listMarkdownFiles(domainDir))))
  }

  return lines.join('\n') + '\n'
}

const main = () => {
  const indexPath = path.join(ROOT, 'docs/README.md')
  const generated = generateIndex(ROOT)

  if (process.argv.includes('--check')) {
    const current = fs.existsSync(indexPath) ? fs.readFileSync(indexPath, 'utf8') : ''
    if (current !== generated) {
      console.error('docs/README.md is stale — run `pnpm docs:index` and commit the result.')
      process.exit(1)
    }
    console.log('Docs index OK.')
    return
  }

  fs.writeFileSync(indexPath, generated)
  console.log('Wrote docs/README.md.')
}

if (require.main === module) main()
